### ISSUE TITLE
git - change was ignored and module was not released

### ISSUE THREAD

**Issue by Dhana-Krishnasamy** [danielflower/multi-module-maven-release-plugin#13] opened 2015-10-05 12:30 UTC
Hi,
I had singe character changes in two lines of my protofile. The plugin ignored it and didnt release the version. Later when I reordered multiple lines, it did detect the change and released it.  Btw this is in version 1.2.0.

**Comment by danielflower** [comment] 2015-10-18 14:48
Yes, this seems to be an outstanding problem where jgit isn't reporting changes. Haven't been able to reproduce yet unfortunately.

**Comment by danielflower** [comment] 2015-10-21 14:45
It's possible this is fixed in 1.4.2 but I wasn't able to reproduce it in a test, so can't be sure.

**Comment by danielflower** [comment] 2016-02-18 15:31
From my own experience, I think this is sorted now so am closing this.

**Closed by danielflower** 2016-02-18 15:31 UTC
