### ISSUE TITLE
Git submodules are detected as uncommited

### ISSUE THREAD

**Issue by stromnet** [danielflower/multi-module-maven-release-plugin#22] opened 2016-03-04 07:39 UTC
When building from an otherwise clean checkout, the plugin complains that my submodule has Uncommited changes.
Happens both when submodule is NOT inited/checked out (which is good), but also when it is checked out and untouched/up to date.

**Comment by danielflower** [comment] 2016-03-06 04:01
Closing as a duplicate of #17 (will reopen if you think it's not a duplicate)

**Closed by danielflower** 2016-03-06 04:01 UTC
