### ISSUE TITLE
can not find the reason for the MissingArgumentException 

### ISSUE THREAD

**Issue by ixtrader** [danielflower/multi-module-maven-release-plugin#30] opened 2016-06-07 16:55 UTC
I am trying to use your multi-module-maven-release-plugin  Version 1.4.6 or 2.0.3 for the very first time. But i cant get it to work. The releaser:release goal throws the following error. Any Idea?

[releasererror.txt](https://github.com/danielflower/multi-module-maven-release-plugin/files/303108/releasererror.txt)

**Comment by danielflower** [comment] 2016-06-19 14:19
Hi, I haven't been able to reproduce, but is something related to the fact that you are just trying to release a single module instead of all. Sorry I don't have more than that right now.

**Comment by danielflower** [comment] 2019-01-27 08:56
Closing due to age. Please re-open if this persists using the latest version.

**Closed by danielflower** 2019-01-27 08:56 UTC
