### ISSUE TITLE
Release failing 

### ISSUE THREAD

**Issue by douglassparker** [danielflower/multi-module-maven-release-plugin#49] opened 2017-03-23 23:18 UTC
UPDATE: The problem was caused because 2 modules had the same artifactId. Consider changing the tag format from artifactId-version to groupId-artifactId-version.     

#This plugin looks great. I confirmed it works on a small project, then tried a larger project. The structure is:
-parent
--entity
---common
---order
--repository
--service
----empdaemon
----order
--util
Initially, all versions are 1.0-SNAPSHOT, I committed and pushed the changes. Then I tried to release. The output is shown below. I am at a loss as to how to proceed. Any help would be appreciated.
$ mvn releaser:release
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] parent
[INFO] entity
[INFO] common
[INFO] order
[INFO] util
[INFO] repository
[INFO] service
[INFO] empdaemon
[INFO] order
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building parent 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- multi-module-maven-release-plugin:2.1.2:release (default-cli) @ parent ---
[INFO] Will use version 1.0.0 for parent as it has changed since the last release.
[INFO] Releasing entity 1.0.0 as parent has changed.
[INFO] Releasing common 1.0.0 as entity has changed.
[INFO] Releasing order 1.0.0 as entity has changed.
[INFO] Releasing util 1.0.0 as parent has changed.
[INFO] Releasing repository 1.0.0 as parent has changed.
[INFO] Releasing service 1.0.0 as parent has changed.
[INFO] Releasing empdaemon 1.0.0 as util has changed.
[INFO] Releasing order 1.0.0 as order has changed.
[INFO] Going to release parent 1.0.0
[INFO] Going to release entity 1.0.0
[INFO] Going to release common 1.0.0
[INFO] Going to release order 1.0.0
[INFO] Going to release util 1.0.0
[INFO] Going to release repository 1.0.0
[INFO] Going to release service 1.0.0
[INFO] Going to release empdaemon 1.0.0
[INFO] Going to release order 1.0.0
[INFO] About to tag the repository with parent-1.0.0
[INFO] About to tag the repository with entity-1.0.0
[INFO] About to tag the repository with common-1.0.0
[INFO] About to tag the repository with order-1.0.0
[INFO] About to tag the repository with util-1.0.0
[INFO] About to tag the repository with repository-1.0.0
[INFO] About to tag the repository with service-1.0.0
[INFO] About to tag the repository with empdaemon-1.0.0
[INFO] About to tag the repository with order-1.0.0
[ERROR]
[ERROR]
[ERROR]
[ERROR] ************************************
[ERROR] Could not execute the release plugin
[ERROR] ************************************
[ERROR]
[ERROR]
[ERROR] There was an error while accessing the Git repository. The error returned from git was:
[ERROR] tag 'Tag={
object 2e7d3636dd683f1e88f95d85e98d51f19b9daa81
type commit
tag order-1.0.0
tagger PersonIdent[parker.douglass, douglass.parker@level3.com, Thu Mar 23 16:57:49 2017 -0600]

{"version":"1.0","buildNumber":"0"}}' already exists
[ERROR] Stack trace:
[ERROR] org.eclipse.jgit.api.errors.RefAlreadyExistsException: tag 'Tag={
object 2e7d3636dd683f1e88f95d85e98d51f19b9daa81
type commit
tag order-1.0.0
tagger PersonIdent[parker.douglass, douglass.parker@level3.com, Thu Mar 23 16:57:49 2017 -0600]

{"version":"1.0","buildNumber":"0"}}' already exists
        at org.eclipse.jgit.api.TagCommand.updateTagRef(TagCommand.java:193)
        at org.eclipse.jgit.api.TagCommand.call(TagCommand.java:164)
        at com.github.danielflower.mavenplugins.release.AnnotatedTag.saveAtHEAD(AnnotatedTag.java:76)
        at com.github.danielflower.mavenplugins.release.LocalGitRepo.tagRepo(LocalGitRepo.java:113)
        at com.github.danielflower.mavenplugins.release.LocalGitRepo.tagRepoAndPush(LocalGitRepo.java:100)
        at com.github.danielflower.mavenplugins.release.ReleaseMojo.tagAndPushRepo(ReleaseMojo.java:174)
        at com.github.danielflower.mavenplugins.release.ReleaseMojo.execute(ReleaseMojo.java:125)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.
java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

[ERROR]
[ERROR]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] parent ............................................. FAILURE [ 12.558 s]
[INFO] entity ............................................. SKIPPED
[INFO] common ............................................. SKIPPED
[INFO] order .............................................. SKIPPED
[INFO] util ............................................... SKIPPED
[INFO] repository ......................................... SKIPPED
[INFO] service ............................................ SKIPPED
[INFO] empdaemon .......................................... SKIPPED
[INFO] order .............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.985 s
[INFO] Finished at: 2017-03-23T16:57:49-06:00
[INFO] Final Memory: 35M/346M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.danielflower.mavenplugins:multi-module-maven-release-plugin:2.1.2:release (def
ault-cli) on project parent: Could not release due to a Git error -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by danielflower** [comment] 2017-04-16 10:06
Closing as duplicate of #50

**Closed by danielflower** 2017-04-16 10:06 UTC
